//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioPerfil
    {
        public UsuarioPerfil()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int IdUsuarioPerfil { get; set; }
        public byte[] FotoPerfil { get; set; }
        public string EstadoPerfil { get; set; }
        public Nullable<int> ScoreJugador { get; set; }
        public Nullable<int> ScoreObservador { get; set; }
        public Nullable<int> ScoreGlobal { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
