//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int IdUsuario { get; set; }
        public string Usuario1 { get; set; }
        public string Contrasena { get; set; }
        public string NombreCompleto { get; set; }
        public string Mail { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> IdUsuarioPerfil { get; set; }
        public Nullable<int> IdUsuarioSeguridad { get; set; }
    
        public virtual UsuarioPerfil UsuarioPerfil { get; set; }
        public virtual UsuarioSeguridad UsuarioSeguridad { get; set; }
    }
}
