//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpartanDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioSeguridad
    {
        public UsuarioSeguridad()
        {
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int IdUsuarioSeguridad { get; set; }
        public string PreguntaSecreta { get; set; }
        public string RespuestaSecreta { get; set; }
    
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}
